version: '3.7'
services:
  bot:
    container_name: praise-the-sun-bot
    image: cr.yandex/crplsbd61fa1sn0gvmhe/praise-the-sun-bot:0.1.2
    restart: always
    environment:
      BOT_TOKEN: ${{ env.BOT_TOKEN }}
      BOT_NAME: PraiseSunBot
      DATA_PATH: /data
    volumes:
      - /data
